### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by GeniusSu** [thespacedoctor/fundamentals#1]
import numpy as np
import query
import statsmodels.api as sm
import scipy.stats as stats
from statsmodels import regression
import matplotlib.pyplot as plt
import pandas as pd
import talib
import fundamentals

dp = get_fundamentals(query(fundamentals.eod_derivative_indicator.market_cap,fundamentals.financial_indicator.book_value_per_share,fundamentals.financial_indicator.return_on_equity, fundamentals.balance_sheet.total_assets),'2017-06-01','40q')

**here's the error message**

 File "/Users/GeniusSu/Library/Python/3.6/lib/python/site-packages/fundamentals/__init__.py", line 1, in <module>
    from __version__ import __version__
ModuleNotFoundError: No module named '__version__'

**Comment by thespacedoctor** [comment]
It seems you have the wrong `fundamentals` package here. The `fundamentals` package you require seems to deal with finance - definitely not my package! Hope you find what you're looking for.

**Comment by GeniusSu** [comment]
thank you so much! 






Sent with Unibox
